### 2.1 データの読み込み　（topic_info2.csv）

In [2]:
import pandas as pd

# データの読み込み
df = pd.read_csv('../dataset/topic_info3.csv')
df.head()

,patent_number,patent_name,date,corporation,ipc,lead_ipc,fi,fterm,keyword,description,year,month,description_embedding,metadata_embedding,lead_inventor,inventors,year_month,topic_id,sim_score
0,特開2001-209692,施設管理システム,200001,['清水建設株式会社'],"['G06F 17/30 (2006.01)', 'G06Q 50/00 (...",G06F 17/30 (2006.01),"['G06F 17/30 170C', 'G06F 17/60 122C', 'G0...","['5B049BB05', '5B049CC02', '5B049CC45', '5B049...","['情報', 'すべて', '有効']",施設施工者が施設管理の情報をすべてにわたりデジタル情報化し、施設所有者に有効な施設管理情報を...,2000,1,"[0.03135940060019493, -0.0030927385669201612, ...",[ 0.2919243 -0.18772289 0.21053162 0.224033...,中島 亨,"中島 亨,竹島育朗",2000-01-01,1,0.906706
1,特開2001-205110,ドラフトチャンバ,200001,['大成建設株式会社'],[],B01L 1/00 (2006.01),[],[],"['化学物質', '作業室', '空調機', '清浄', '作業環境', '実験']",化学物質を取り扱うためのフードを備えたドラフトチャンバにおいて、作業室に空調設備を設けなくて...,2000,1,"[0.013121270574629307, -0.02321396768093109, -...",[ 0.27802473 -0.2309001 0.12717132 0.175692...,森内 裕之,森内 裕之,2000-01-01,0,0.909713
2,特開2001-206757,コンクリート組成物及びトンネル覆工工法,200001,['西松建設株式会社'],"['E21D 11/10 (2006.01)', 'C04B 28/02 (...",E21D 11/10 (2006.01),"['E21D 11/10 D', 'E21D 11/10 Z', 'C0...","['2D055DB00', '2D055KA00', '4G012PA27', '4G012...","['吹付けコンクリート', '品質', 'コストダウン', '作業環境', 'コンクリート組...",吹付けコンクリートの品質、施工性を向上させると共に、コストダウンを達成し、さらには口内粉塵の...,2000,1,"[0.0016511422581970692, 0.016119062900543213, ...",[ 0.30306432 -0.20834202 0.12808324 0.177891...,田浦 一英,"田浦 一英,山本 康博,藤川 可",2000-01-01,3,0.932252
3,特開2001-207423,後退パラペット型堤体の衝撃波力低減工法,200001,"['五洋建設株式会社', '中国電力株式会社']",['E02B 3/06 (2006.01)'],E02B 3/06 (2006.01),['E02B 3/06 301'],"['2D018BA11', '2D118AA11', '2D118DA01', '2D118...","['従来', '作用']",従来の後退パラペット型堤体においては、後退パラペットに作用する波力および転倒モーメントが大き...,2000,1,"[0.03772636130452156, 0.0183484498411417, -0.0...",[ 0.23017973 -0.32329643 0.08356746 0.327914...,関本 恒浩,"関本 恒浩,森屋 陽一,佐貫 宏,川俣 奨,泉 雄士,金田 時義,藤原 茂範,平岡 順...",2000-01-01,5,0.882758
4,特開2001-208409,空調用の流路切換装置及びそれを備えた空調機,200001,"['株式会社日建設計', '新晃工業株式会社']",['F24F 13/02 (2006.01)'],F24F 13/02 (2006.01),['F24F 13/02 D'],"['3L080AA02', '3L080AA04']","['空調システム', '流路']",空調システムに使用される流路の切換装置を簡略化する,2000,1,"[0.009848109446465969, 0.027212440967559814, -...",[ 0.25761563 -0.20579714 0.19196749 0.156607...,橋本 直樹,"橋本 直樹,稲川 健",2000-01-01,0,0.914396

In [3]:
df.shape

(42789, 19)

In [4]:
filtered_df = df[(df['topic_id'] == 0)]

In [5]:
sorted_df = filtered_df.sort_values(by='sim_score', ascending=False)
top_5_results = sorted_df.head(10)
top_5_results

,patent_number,patent_name,date,corporation,ipc,lead_ipc,fi,fterm,keyword,description,year,month,description_embedding,metadata_embedding,lead_inventor,inventors,year_month,topic_id,sim_score
18323,特開2008-256269,空調方法,200704,['高砂熱学工業株式会社'],"['F24F 7/08 (2006.01)', 'F24F 7/007 (...",F24F 7/08 (2006.01),"['F24F 7/08 Z', 'F24F 7/007 B', 'F2...","['3L056BD04', '3L056BD07', '3L080AA05']","['送風機', '空調システム']",吹き出し誘引量を適性に保ちながら送風機の搬送動力を低減できる空調システムを提供する,2007,4,"[-0.004739166237413883, 0.007016780320554972, ...",[ 0.2604899 -0.2116221 0.20080718 0.164451...,三橋 太,"三橋 太,守屋 寛之,木村 健太郎",2007-04-01,0,0.945113
40589,特開2020-133181,構造物,201902,['株式会社竹中工務店'],"['E04B 1/76 (2006.01)', 'E04B 1/70 (...",E04B 1/76 (2006.01),"['E04B 1/76 500F', 'E04B 1/70 B', 'E0...","['2E001DA01', '2E001DB02', '2E001DD12', '2E001...","['省エネ', '室内環境', '構造物']",省エネルギーを図りつつ、室内環境を制御することができる構造物を提供する,2019,2,"[0.006471855100244284, 0.018053846433758736, -...",[ 0.29786813 -0.24143982 0.15515663 0.212870...,花岡 郁哉,"花岡 郁哉,福西 英知,市倉 隆平,リー アリック,吉田 徹",2019-02-01,0,0.945029
25782,特開2012-225615,低湿度室の空調システム,201104,['清水建設株式会社'],"['F24F 11/02 (2006.01)', 'F24F 3/14 (...",F24F 11/02 (2006.01),"['F24F 11/02 S', 'F24F 3/14', 'F24F 11/0...","['3L053BC03', '3L060CC11', '3L060DD01', '3L260...","['湿度', '消費エネルギー', '空調システム']",湿度の変動を抑えるのに要する消費エネルギーが少なくて済む低湿度室の空調システムを提供する,2011,4,"[-0.009370774962008, 0.009847662411630154, -0....",[ 0.28602707 -0.21935916 0.17459312 0.187377...,梶間 智明,"梶間 智明,鈴木 令,田中 勲",2011-04-01,0,0.944509
41329,特開2020-200970,置換換気空調システム,201906,['清水建設株式会社'],"['F24F 13/08 (2006.01)', 'F24F 7/10 (...",F24F 13/08 (2006.01),"['F24F 13/08 A', 'F24F 7/10 Z', 'F2...","['3L080BB01', '3L080BA01', '3L080BB02', '3L081...",['設置コスト'],居住域の空間利用効率を向上するとともに、設置コストを低減することができる置換換気空調システム...,2019,6,"[0.013033679686486721, 0.001994782593101263, -...",[ 0.25606096 -0.11607853 0.23257089 0.114275...,三浦 靖弘,"三浦 靖弘,笠原 真紀子,若杉 晋吾,野村 圭吾,藤田 渉,村上 宏次,長谷部 弥,川上 梨沙",2019-06-01,0,0.944399
24416,特開2012-026683,吹出口装置,201007,['大成建設株式会社'],['F24F 13/06 (2006.01)'],F24F 13/06 (2006.01),['F24F 13/06 A'],"['3L080BA01', '3L080BB01']","['居住者', '快適', '吹出口装置']",居住者にとって快適な空気調和状態を容易に実現できる吹出口装置を提供すること,2010,7,"[0.013613097369670868, 0.004245914984494448, -...",[ 0.26742917 -0.1310645 0.25372648 0.183183...,和手 俊明,"和手 俊明,小林 光,梶山 隆史,大木 泰祐,張本 和芳,田中 拓也",2010-07-01,0,0.944357
22545,特開2011-017517,置換空調システム,200907,['高砂熱学工業株式会社'],"['F24F 3/153 (2006.01)', 'F24F 3/14 (...",F24F 3/153 (2006.01),"['F24F 3/153', 'F24F 11/02 102J', 'F24F 3/...","['3L053BC02', '3L060AA03', '3L060AA06', '3L060...","['除湿', '空気', 'エネルギー']",除湿のために過冷却した空気を再熱する際のエネルギーを低減することが可能な置換空調システムを提供する,2009,7,"[0.023885175585746765, -0.004320499021559954, ...",[ 3.14610362e-01 -2.54004836e-01 1.77750960e-...,平井 浩二,平井 浩二,2009-07-01,0,0.944286
36532,特開2018-141566,放射空調システム,201702,['清水建設株式会社'],"['F24F 11/62 (2018.01)', 'F24F 1/0047 (...",F24F 11/62 (2018.01),"['F24F 11/62', 'F24F 1/0047', 'F24F 5/00 1...","['3L050BC10', '3L260CB63', '3L260CB40', '3L260...","['コスト', '安定', '放射空調システム']",コストをかけることなく、安定した応答性がよい制御を行うことが可能な放射空調システムを提供する,2017,2,"[0.013923091813921928, -0.001150407362729311, ...",[ 0.28398734 -0.21205851 0.18415189 0.221844...,伊藤 清,伊藤 清,2017-02-01,0,0.944162
39899,特開2020-060344,空調機器の冷却装置,201810,"['株式会社竹中工務店', '新晃工業株式会社']","['F24F 7/08 (2006.01)', 'F24F 13/26 (...",F24F 1/0035 (2019.01),"['F24F 1/00 431A', 'F24F 7/08 101Z', 'F2...",[],"['不快', '室内', '空調環境', '空調機器', '冷却システム']",不快な空気感を在室者に与えることなく均一な室内の空調環境を形成する空調機器の冷却装置を提供する,2018,10,"[0.005690326914191246, -0.004841938149183989, ...",[ 0.23973429 -0.21228826 0.19315098 0.146262...,村瀬 勇人,"村瀬 勇人,後藤 和博,田中 真,小池 正浩,芝原 崇慶,高橋 幹雄,和田 一樹,船木 昭二...",2018-10-01,0,0.944099
16501,特開2007-292365,空調換気システム,200604,['高砂熱学工業株式会社'],"['F24F 11/02 (2006.01)', 'F24F 7/10 (...",F24F 11/02 (2006.01),"['F24F 11/02 102J', 'F24F 7/10 Z', 'F2...","['3L060CC03', '3L060EE26', '3L060EE27', '3L260...",['空調負荷'],空調負荷の低減と換気性の改善が可能な空調換気システムを提供する,2006,4,"[0.004043634980916977, -0.005132385063916445, ...",[ 0.17402525 -0.1038985 0.19464532 0.112639...,三橋 太,"三橋 太,木村 健太郎,守屋 寛之",2006-04-01,0,0.944070
30202,特開2015-078808,空気熱源機を用いた熱回収システム,201310,['高砂熱学工業株式会社'],"['F24F 3/044 (2006.01)', 'F24H 1/00 (...",F24F 3/044 (2006.01),['F24F 3/044'],"['3L122AA02', '3L122AA23', '3L122AC14']","['建物', '廃熱', '空調システム']",建物で発生した廃熱を効率よく利用できる空調システムを提供する,2013,10,"[0.02162475325167179, 0.016707733273506165, -0...",[ 0.2663367 -0.22646073 0.15890959 0.179630...,桑原 健次,桑原 健次,2013-10-01,0,0.943974

In [6]:
# トピックごとの特許数
print("\nトピックごとの特許数:")
topic_counts = df['topic_id'].value_counts().sort_index()
print(topic_counts)

トピックごとの特許数:
topic_id
0    4000
1    5208
2    5934
3    7072
4     983
5    8515
6     831
7    1443
8    7858
9     945
Name: count, dtype: int64

In [7]:
# 年月の分布を確認
print("年月の範囲:")
print(f"最小: {df['year_month'].min()}")
print(f"最大: {df['year_month'].max()}")

年月の範囲:
最小: 2000-01-01
最大: 2021-06-01

### 2.2 発明者とトピックのグラフ構築の際のエッジの重みを計算

「発明者inventorが、技術トピックtopicに対してどれくらい深く関わっているか」
sim_score (特許のトピック適合度) × RoleWeight (筆頭/共同の重み)

In [8]:
df.head(5)

,patent_number,patent_name,date,corporation,ipc,lead_ipc,fi,fterm,keyword,description,year,month,description_embedding,metadata_embedding,lead_inventor,inventors,year_month,topic_id,sim_score
0,特開2001-209692,施設管理システム,200001,['清水建設株式会社'],"['G06F 17/30 (2006.01)', 'G06Q 50/00 (...",G06F 17/30 (2006.01),"['G06F 17/30 170C', 'G06F 17/60 122C', 'G0...","['5B049BB05', '5B049CC02', '5B049CC45', '5B049...","['情報', 'すべて', '有効']",施設施工者が施設管理の情報をすべてにわたりデジタル情報化し、施設所有者に有効な施設管理情報を...,2000,1,"[0.03135940060019493, -0.0030927385669201612, ...",[ 0.2919243 -0.18772289 0.21053162 0.224033...,中島 亨,"中島 亨,竹島育朗",2000-01-01,1,0.906706
1,特開2001-205110,ドラフトチャンバ,200001,['大成建設株式会社'],[],B01L 1/00 (2006.01),[],[],"['化学物質', '作業室', '空調機', '清浄', '作業環境', '実験']",化学物質を取り扱うためのフードを備えたドラフトチャンバにおいて、作業室に空調設備を設けなくて...,2000,1,"[0.013121270574629307, -0.02321396768093109, -...",[ 0.27802473 -0.2309001 0.12717132 0.175692...,森内 裕之,森内 裕之,2000-01-01,0,0.909713
2,特開2001-206757,コンクリート組成物及びトンネル覆工工法,200001,['西松建設株式会社'],"['E21D 11/10 (2006.01)', 'C04B 28/02 (...",E21D 11/10 (2006.01),"['E21D 11/10 D', 'E21D 11/10 Z', 'C0...","['2D055DB00', '2D055KA00', '4G012PA27', '4G012...","['吹付けコンクリート', '品質', 'コストダウン', '作業環境', 'コンクリート組...",吹付けコンクリートの品質、施工性を向上させると共に、コストダウンを達成し、さらには口内粉塵の...,2000,1,"[0.0016511422581970692, 0.016119062900543213, ...",[ 0.30306432 -0.20834202 0.12808324 0.177891...,田浦 一英,"田浦 一英,山本 康博,藤川 可",2000-01-01,3,0.932252
3,特開2001-207423,後退パラペット型堤体の衝撃波力低減工法,200001,"['五洋建設株式会社', '中国電力株式会社']",['E02B 3/06 (2006.01)'],E02B 3/06 (2006.01),['E02B 3/06 301'],"['2D018BA11', '2D118AA11', '2D118DA01', '2D118...","['従来', '作用']",従来の後退パラペット型堤体においては、後退パラペットに作用する波力および転倒モーメントが大き...,2000,1,"[0.03772636130452156, 0.0183484498411417, -0.0...",[ 0.23017973 -0.32329643 0.08356746 0.327914...,関本 恒浩,"関本 恒浩,森屋 陽一,佐貫 宏,川俣 奨,泉 雄士,金田 時義,藤原 茂範,平岡 順...",2000-01-01,5,0.882758
4,特開2001-208409,空調用の流路切換装置及びそれを備えた空調機,200001,"['株式会社日建設計', '新晃工業株式会社']",['F24F 13/02 (2006.01)'],F24F 13/02 (2006.01),['F24F 13/02 D'],"['3L080AA02', '3L080AA04']","['空調システム', '流路']",空調システムに使用される流路の切換装置を簡略化する,2000,1,"[0.009848109446465969, 0.027212440967559814, -...",[ 0.25761563 -0.20579714 0.19196749 0.156607...,橋本 直樹,"橋本 直樹,稲川 健",2000-01-01,0,0.914396

In [9]:
import pandas as pd
import numpy as np
import torch
from torch_geometric.data import Data

# --- 設定 ---
SIM_SCORE_THRESHOLD = 0.5 
LEAD_WEIGHT = 1.0  # 筆頭発明者の重み係数
CO_WEIGHT = 0.5    # 共同発明者の重み係数

def preprocess_weighted_edges(df):

    print("Lead Inventor列を使用した重み付きデータ作成中...")
    
    # 必要な列をコピー (SettingWithCopyWarning回避)
    sub_df = df[['year_month', 'inventors', 'lead_inventor', 'topic_id', 'sim_score']].copy()
    
    # sim_scoreによる足切り
    sub_df = sub_df[sub_df['sim_score'] >= SIM_SCORE_THRESHOLD]
    
    # 発明者リストのパース関数
    def parse_inventors(x):
        if isinstance(x, list): return x
        if pd.isna(x) or x == "": return []
        # 文字列の場合、全角/半角カンマで分割
        return [i.strip() for i in str(x).replace('，', ',').split(',') if i.strip()]

    processed_rows = []
    
    for _, row in sub_df.iterrows():
        # 発明者リスト取得
        invs = parse_inventors(row['inventors'])
        if not invs:
            continue
            
        # 筆頭発明者名取得 (空白除去)
        lead_name = str(row['lead_inventor']).strip() if pd.notna(row['lead_inventor']) else ""
        
        for inv_name in invs:
            inv_name_clean = inv_name.strip()
            
            # 【重要】名前の一致判定
            is_lead = (inv_name_clean == lead_name)
            
            # 役割による重み係数
            role_w = LEAD_WEIGHT if is_lead else CO_WEIGHT
            
            # 最終的なエッジ重み = トピック類似度 * 役割重み
            # sim 0.9 * lead 1.0 = 0.9 （類似度 * 筆頭発明者）
            # sim 0.9 * co 0.5 = 0.45 （類似度 * 共同発明者)
            final_weight = row['sim_score'] * role_w
            
            processed_rows.append({
                'year_month': row['year_month'],
                'inventor': inv_name_clean,
                'topic_id': int(row['topic_id']),
                'weight': final_weight,
                'is_lead': is_lead # 確認用
            })
            
    new_df = pd.DataFrame(processed_rows)
    # 日付型変換
    new_df['year_month'] = pd.to_datetime(new_df['year_month'], format='%Y-%m-%d') # 必要に応じてフォーマット調整
    
    print(f"処理完了: エッジ総数 {len(new_df)}")
    print(f"うち筆頭発明者エッジ数: {new_df['is_lead'].sum()}")
    
    return new_df

weighted_edges_df = preprocess_weighted_edges(df)
print(weighted_edges_df.head())

/home/nakamuraroi/.local/lib/python3.8/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/nakamuraroi/.local/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/nakamuraroi/.local/lib/python3.8/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/nakamuraroi/.local/lib/python3.8/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
/home/nakamuraroi/.local/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Lead Inventor列を使用した重み付きデータ作成中...
処理完了: エッジ総数 160807
うち筆頭発明者エッジ数: 42787
  year_month inventor  topic_id    weight  is_lead
0 2000-01-01     中島　亨         1  0.906706     True
1 2000-01-01     竹島育朗         1  0.453353    False
2 2000-01-01    森内　裕之         0  0.909713     True
3 2000-01-01    田浦　一英         3  0.932252     True
4 2000-01-01    山本　康博         3  0.466126    False

In [10]:
weighted_edges_df

       year_month inventor  topic_id    weight  is_lead
0      2000-01-01     中島　亨         1  0.906706     True
1      2000-01-01     竹島育朗         1  0.453353    False
2      2000-01-01    森内　裕之         0  0.909713     True
3      2000-01-01    田浦　一英         3  0.932252     True
4      2000-01-01    山本　康博         3  0.466126    False
...           ...      ...       ...       ...      ...
160802 2021-05-01   岩田  曉洋         8  0.467216    False
160803 2021-05-01   渡邉  祐一         8  0.467216    False
160804 2021-05-01    渡邊  徹         8  0.467216    False
160805 2021-06-01   高木  政美         5  0.937220     True
160806 2021-06-01    塚田  乙         5  0.468610    False

[160807 rows x 5 columns]

### 2.3 重み付きグラフの構築

In [11]:
# 1. ノードIDのマッピング作成
# 全データからユニークなリストを作成
all_inventors = sorted(list(set(weighted_edges_df['inventor'])))
all_topics = sorted(list(set(weighted_edges_df['topic_id'])))

num_inventors = len(all_inventors)
num_topics = len(all_topics)
total_nodes = num_inventors + num_topics

print(f"発明者数: {num_inventors}")
print(f"トピック数: {num_topics}")
print(f"総ノード数: {total_nodes}")

発明者数: 39627
トピック数: 10
総ノード数: 39637

In [12]:
# ID辞書の作成
# 発明者ID: 0 〜 (num_inventors - 1)
inventor_to_idx = {name: i for i, name in enumerate(all_inventors)}

# トピックID: num_inventors 〜 (total_nodes - 1)
topic_to_idx = {tid: i + num_inventors for i, tid in enumerate(all_topics)}

# 確認: 最初の5人のマッピングを表示
print("\n--- IDマッピング例 (発明者) ---")
print(list(inventor_to_idx.items())[:5])

print("\n--- IDマッピング例 (トピック) ---")
print(list(topic_to_idx.items())[:5])

--- IDマッピング例 (発明者) ---
[('▲あべ▼木\u3000周作', 0), ('▲あべ▼松\u3000忠', 1), ('▲から▼▲さき▼\u3000和孝', 2), ('▲からさき▼\u3000和孝', 3), ('▲から崎▼\u3000和孝', 4)]

--- IDマッピング例 (トピック) ---
[(0, 39627), (1, 39628), (2, 39629), (3, 39630), (4, 39631)]

In [13]:
# 2. 年ごとにグループ化
year_groups = weighted_edges_df.groupby(weighted_edges_df['year_month'].dt.year)

# 確認: どんな年が含まれているか
available_years = sorted(year_groups.groups.keys())
print(f"データに含まれる年: {available_years}")

# テスト用に最初の年を取得して中身を見てみる
test_year = available_years[0]
test_group = year_groups.get_group(test_year)

print(f"\n--- {test_year}年のデータプレビュー ({len(test_group)}件) ---")
print(test_group[['inventor', 'topic_id', 'weight']].head())

データに含まれる年: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

--- 2000年のデータプレビュー (12121件) ---
  inventor  topic_id    weight
0     中島　亨         1  0.906706
1     竹島育朗         1  0.453353
2    森内　裕之         0  0.909713
3    田浦　一英         3  0.932252
4    山本　康博         3  0.466126

In [14]:
# 3. エッジの重みの集計  (test_year分のみ実行)
edge_weights_dict = {}
active_nodes = set()

print(f"--- {test_year}年の重み集計を開始 ---")

for _, row in test_group.iterrows():
    # IDに変換
    if row['inventor'] not in inventor_to_idx or row['topic_id'] not in topic_to_idx:
        continue

    u = inventor_to_idx[row['inventor']]
    v = topic_to_idx[row['topic_id']]
    w = row['weight']

    # ペアをソートしてタプル化 (小さいID, 大きいID)
    pair = tuple(sorted((u, v)))

    if pair not in edge_weights_dict:
        edge_weights_dict[pair] = 0.0

    # 重みを加算
    edge_weights_dict[pair] += w

    active_nodes.add(u)
    active_nodes.add(v)

# 集計結果の確認（最初の5件）
print(f"集計後のユニークなエッジ数: {len(edge_weights_dict)}")
print("エッジ重みのサンプル（ノードIDペア: 重み):")
for i, (pair, weight) in enumerate(edge_weights_dict.items()):
    if i>=5: break
    inv_id, top_id = pair 

    inv_name = all_inventors[inv_id] if inv_id < num_inventors else "Topic?"
    top_name = all_topics[top_id - num_inventors] if top_id >= num_inventors else "Inv?"

    print(f"  {pair} ({inv_name} - Topic {top_name}): {weight:.4f}")

--- 2000年の重み集計を開始 ---
集計後のユニークなエッジ数: 8573
エッジ重みのサンプル（ノードIDペア: 重み):
  (1560, 39628) (中島　亨 - Topic 1): 0.9067
  (31046, 39628) (竹島育朗 - Topic 1): 0.4534
  (23019, 39627) (森内　裕之 - Topic 0): 0.9097
  (28527, 39630) (田浦　一英 - Topic 3): 0.9323
  (14924, 39630) (山本　康博 - Topic 3): 0.4661

In [15]:
# 「特定の発明者」と「特定の技術トピック」のIDの組み合わせ
pair

(33273, 39630)

In [16]:
# 4. 全期間のグラフ構築を実行
graphs = {}

print("全期間のグラフ構築を開始...")

for year, group in year_groups:
    edges_weights_dict = {}
    active_nodes = set()

    for _, row in group.iterrows():
        u = inventor_to_idx[row['inventor']]
        v = topic_to_idx[row['topic_id']]
        w = row['weight']

        pair = tuple(sorted((u, v)))

        if pair not in edge_weights_dict:
            edge_weights_dict[pair] = 0.0
        edge_weights_dict[pair] += w

        active_nodes.add(u)
        active_nodes.add(v)

    if not edge_weights_dict:
        continue

    # COO形式 (edge_index) と edge_weight の作成
    edges = []
    weights = []

    for (u, v), w in edge_weights_dict.items():
        # 双方向 (u -> v)
        edges.append([u, v])
        weights.append(w)
        # 双方向 (v -> u)
        edges.append([v, u])
        weights.append(w)
        
    # Tensor変換
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    edge_weight = torch.tensor(weights, dtype=torch.float32)
    
    # アクティブなノードのマスク作成
    active_mask = torch.zeros(total_nodes, dtype=torch.bool)
    active_mask[list(active_nodes)] = True

    # Dataオブジェクト作成
    graphs[year] = Data(
        edge_index=edge_index,
        edge_weight=edge_weight,
        num_nodes=total_nodes,
        active_mask=active_mask,
        year=year
    )

print(f"完了: {len(graphs)}年分のグラフ辞書 (graph_dict) が完成しました。")

全期間のグラフ構築を開始...
完了: 22年分のグラフ辞書 (graph_dict) が完成しました。

In [17]:
# edge_index=[始点ノードID, 終点ノードID]
# edge_weight=[エッジの数に対応する強さ]
# num_nodes=[全発明者+全トピック]
# active_mask=[その年に誰が活動していたかを示すマスク]
graphs

{2000: Data(edge_index=[2, 17146], edge_weight=[17146], num_nodes=39637, active_mask=[39637], year=2000),
 2001: Data(edge_index=[2, 28790], edge_weight=[28790], num_nodes=39637, active_mask=[39637], year=2001),
 2002: Data(edge_index=[2, 38788], edge_weight=[38788], num_nodes=39637, active_mask=[39637], year=2002),
 2003: Data(edge_index=[2, 47782], edge_weight=[47782], num_nodes=39637, active_mask=[39637], year=2003),
 2004: Data(edge_index=[2, 55424], edge_weight=[55424], num_nodes=39637, active_mask=[39637], year=2004),
 2005: Data(edge_index=[2, 62420], edge_weight=[62420], num_nodes=39637, active_mask=[39637], year=2005),
 2006: Data(edge_index=[2, 68250], edge_weight=[68250], num_nodes=39637, active_mask=[39637], year=2006),
 2007: Data(edge_index=[2, 73756], edge_weight=[73756], num_nodes=39637, active_mask=[39637], year=2007),
 2008: Data(edge_index=[2, 78870], edge_weight=[78870], num_nodes=39637, active_mask=[39637], year=2008),
 2009: Data(edge_index=[2, 84080], edge_weight=[84080], num_nodes=39637, active_mask=[39637], year=2009),
 2010: Data(edge_index=[2, 89414], edge_weight=[89414], num_nodes=39637, active_mask=[39637], year=2010),
 2011: Data(edge_index=[2, 94336], edge_weight=[94336], num_nodes=39637, active_mask=[39637], year=2011),
 2012: Data(edge_index=[2, 99952], edge_weight=[99952], num_nodes=39637, active_mask=[39637], year=2012),
 2013: Data(edge_index=[2, 105248], edge_weight=[105248], num_nodes=39637, active_mask=[39637], year=2013),
 2014: Data(edge_index=[2, 110166], edge_weight=[110166], num_nodes=39637, active_mask=[39637], year=2014),
 2015: Data(edge_index=[2, 115590], edge_weight=[115590], num_nodes=39637, active_mask=[39637], year=2015),
 2016: Data(edge_index=[2, 121336], edge_weight=[121336], num_nodes=39637, active_mask=[39637], year=2016),
 2017: Data(edge_index=[2, 127076], edge_weight=[127076], num_nodes=39637, active_mask=[39637], year=2017),
 2018: Data(edge_index=[2, 132814], edge_weight=[132814], num_nodes=39637, active_mask=[39637], year=2018),
 2019: Data(edge_index=[2, 138776], edge_weight=[138776], num_nodes=39637, active_mask=[39637], year=2019),
 2020: Data(edge_index=[2, 139924], edge_weight=[139924], num_nodes=39637, active_mask=[39637], year=2020),
 2021: Data(edge_index=[2, 139982], edge_weight=[139982], num_nodes=39637, active_mask=[39637], year=2021)}

In [18]:
# 最終確認用の変数セット
graph_dict = graphs
num_inv = num_inventors
num_top = num_topics

In [19]:
# テストとして1つ中身を確認
last_year = sorted(graphs.keys())[-1]
print(f"\n--- 最終年 ({last_year}) のグラフデータ ---")
print(graphs[last_year])

--- 最終年 (2021) のグラフデータ ---
Data(edge_index=[2, 139982], edge_weight=[139982], num_nodes=39637, active_mask=[39637], year=2021)

### 2.4 モデル定義 (重み対応型 GCN-VGAE)

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torchdiffeq import odeint

print('ライブラリのインポート')

ライブラリのインポート

In [21]:
# 重み対応エンコーダ
class WeightedEncoder(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        # GCNConvは edge_weight を引数に取れます
        self.conv1 = GCNConv(in_channels, hidden_channels * 2)
        self.conv2 = GCNConv(hidden_channels * 2, hidden_channels)
        self.conv_mu = GCNConv(hidden_channels, out_channels)
        self.conv_logvar = GCNConv(hidden_channels, out_channels)
        self.dropout = nn.Dropout(0.2)
        self.batch_norm1 = nn.BatchNorm1d(hidden_channels * 2)
        self.batch_norm2 = nn.BatchNorm1d(hidden_channels)

    def forward(self, x, edge_index, edge_weight):
        # edge_weight を渡すことで、筆頭発明者のリンクを重視して畳み込み
        x = F.relu(self.batch_norm1(self.conv1(x, edge_index, edge_weight)))
        x = self.dropout(x)
        x = F.relu(self.batch_norm2(self.conv2(x, edge_index, edge_weight)))
        x = self.dropout(x)
        return self.conv_mu(x, edge_index, edge_weight), self.conv_logvar(x, edge_index, edge_weight)

In [22]:
# ODE予測器 (潜在空間での時間発展を学習)
class SimpleODEPredictor(nn.Module):
    def __init__(self, latent_dim, hidden_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim + 1, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, latent_dim)
        )
    def forward(self, t, z):
        # 時間 t をベクトル化して結合
        t_vec = t.expand(z.size(0), 1)
        return self.net(torch.cat([z, t_vec], dim=1))

In [23]:
# 発明者-トピック統合モデル
class WeightedInventorTopicModel(nn.Module):
    def __init__(self, num_inventors, num_topics, embedding_dim=64, hidden_dim=32, latent_dim=16):
        super().__init__()
        self.num_inventors = num_inventors
        self.num_topics = num_topics

        # ノードIDに対するEmbedding
        self.inventor_emb = nn.Embedding(num_inventors, embedding_dim)
        self.topic_emb = nn.Embedding(num_topics, embedding_dim)
        nn.init.xavier_normal_(self.inventor_emb.weight)
        nn.init.xavier_normal_(self.topic_emb.weight)

        # 重み対応エンコーダ
        self.encoder = WeightedEncoder(embedding_dim, hidden_dim, latent_dim)
        
        # ODE
        self.ode_func = SimpleODEPredictor(latent_dim, hidden_dim)
        
        # リンク予測 (デコーダ)
        self.link_predictor = nn.Sequential(
            nn.Linear(latent_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1)
        )

    def get_node_features(self, device):
        inv_feats = self.inventor_emb(torch.arange(self.num_inventors, device=device))
        topic_feats = self.topic_emb(torch.arange(self.num_topics, device=device))
        return torch.cat([inv_feats, topic_feats], dim=0)

    def encode(self, edge_index, edge_weight):
        x = self.get_node_features(edge_index.device)
        mu, logvar = self.encoder(x, edge_index, edge_weight)
        
        if self.training:
            std = torch.exp(0.5 * logvar)
            z = mu + torch.randn_like(std) * std
        else:
            z = mu
        return z, mu, logvar

    def decode(self, z, edge_index):
        z_norm = F.normalize(z, p=2, dim=1)
        src, dst = edge_index
        dot = (z_norm[src] * z_norm[dst]).sum(dim=1)
        logits = dot * 10.0
        return torch.sigmoid(logits)
    
    def predict_future(self, z):
        # ODEで未来の状態を予測 (t=0 -> t=1)
        t = torch.tensor([0., 1.0]).to(z.device)
        # odeint は [z(t0), z(t1)] を返すので [-1] で z(t1) を取得
        z_next = odeint(self.ode_func, z, t, method='dopri5')[-1]
        return z_next

### 3.4 model学習実行

In [24]:
import time
from torch_geometric.utils import negative_sampling

# デバイス設定
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# モデル初期化
model = WeightedInventorTopicModel(
    num_inventors=num_inv, 
    num_topics=num_top
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-3)

print("重み付きモデルの学習開始...")
years = sorted(graph_dict.keys())
start_time = time.time()

# 学習ループ
for epoch in range(100):
    model.train()
    total_loss = 0
    
    for i in range(len(years) - 1):
        year_t = years[i]
        year_t1 = years[i+1]
        
        data_t = graph_dict[year_t].to(device)
        data_t1 = graph_dict[year_t1].to(device)
        
        optimizer.zero_grad()
        
        # 1. 重み付きグラフで現在の状態をエンコード
        z_t, mu, logvar = model.encode(data_t.edge_index, data_t.edge_weight)
        
        # 2. 現在のリンク再構成誤差
        pos_pred = model.decode(z_t, data_t.edge_index)
        pos_loss = -torch.log(pos_pred + 1e-15).mean()
        
        # 負例サンプリング
        neg_edge_index = negative_sampling(
            edge_index=data_t.edge_index,
            num_nodes=data_t.num_nodes,
            num_neg_samples=data_t.edge_index.size(1) # 正例と同じ数
        )
        neg_pred = model.decode(z_t, neg_edge_index)
        neg_loss = -torch.log(1 - neg_pred + 1e-15).mean()
        recon_loss = pos_loss + neg_loss

        # 3. KL Divergence
        kl_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
        
        # 4. 未来予測
        z_next = model.predict_future(mu)
        
        # 5. 未来のリンク予測誤差 (t+1 のグラフ構造を予測)
        # --- 5. 未来のリンク予測学習 ---
        if data_t1.edge_index.numel() > 0:
            # (A) 未来の正例
            fut_pos_pred = model.decode(z_next, data_t1.edge_index)
            fut_pos_loss = -torch.log(fut_pos_pred + 1e-15).mean()
            
            # (B) 未来の負例（★ここも追加）
            fut_neg_edge_index = negative_sampling(
                edge_index=data_t1.edge_index,
                num_nodes=data_t1.num_nodes,
                num_neg_samples=data_t1.edge_index.size(1)
            )
            fut_neg_pred = model.decode(z_next, fut_neg_edge_index)
            fut_neg_loss = -torch.log(1 - fut_neg_pred + 1e-15).mean()
            
            future_loss = fut_pos_loss + fut_neg_loss
        else:
            future_loss = 0
            
        # 損失の合計
        loss = recon_loss + 0.0 * kl_loss + 10*future_loss
        
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total_loss += loss.item()
        
    if (epoch+1) % 5 == 0:
        print(f"Epoch {epoch+1}: Total Loss {total_loss:.4f}")

print(f"学習完了 (所要時間: {time.time() - start_time:.2f}秒)")

Using device: cuda
重み付きモデルの学習開始...
Epoch 5: Total Loss 361.5948
Epoch 10: Total Loss 327.2563
Epoch 15: Total Loss 317.0188
Epoch 20: Total Loss 311.9779
Epoch 25: Total Loss 307.6191
Epoch 30: Total Loss 305.1062
Epoch 35: Total Loss 302.0146
Epoch 40: Total Loss 298.6242
Epoch 45: Total Loss 296.8953
Epoch 50: Total Loss 293.3643
Epoch 55: Total Loss 292.5043
Epoch 60: Total Loss 289.9482
Epoch 65: Total Loss 288.6800
Epoch 70: Total Loss 286.6679
Epoch 75: Total Loss 286.1515
Epoch 80: Total Loss 283.1111
Epoch 85: Total Loss 282.7326
Epoch 90: Total Loss 282.4292
Epoch 95: Total Loss 281.1807
Epoch 100: Total Loss 279.2546
学習完了 (所要時間: 260.17秒)

### 3.5 評価と未来予測データの抽出

In [25]:
import pandas as pd
import numpy as np
import torch

# --- 1. 必要な情報の準備 ---

# 最後の2期間（学習の最終ステップ）を取得
years = sorted(graph_dict.keys())
last_year_t = years[-2]
last_year_t1 = years[-1]

data_t = graph_dict[last_year_t].to(device)
data_t1 = graph_dict[last_year_t1].to(device) # 検証用データ（実際のリンク）

num_inventors = model.num_inventors
num_topics = model.num_topics
total_nodes = num_inventors + num_topics

print(f"最終学習期間: {last_year_t}")
print(f"予測対象期間: {last_year_t1}")

最終学習期間: 2020
予測対象期間: 2021

In [26]:
# --- 2. 実際のリンクセット (正解データ) の作成 ---

actual_edges = data_t1.edge_index.t().cpu().numpy()

actual_links_set = set()
for u, v in actual_edges:
    if u < num_inventors and v >= num_inventors:
        actual_links_set.add((u, v))

print(f"正解リンク（Inventor->Topic, t+1期間）の数: {len(actual_links_set)}")

正解リンク（Inventor->Topic, t+1期間）の数: 69991

In [27]:
# --- 3. 未来予測の実行 ---

model.eval()
with torch.no_grad():
    # t時点のグラフ構造から潜在ベクトル mu をエンコード
    _, mu_t, _ = model.encode(data_t.edge_index, data_t.edge_weight)
    
    # mu_t をODEに通し、t+1時点の潜在ベクトルを予測
    z_pred = model.predict_future(mu_t)

# マッピング情報の再構築 (セル2の処理に依存)
all_inventors = sorted(list(set(weighted_edges_df['inventor'])))
all_topics = sorted(list(set(weighted_edges_df['topic_id'])))
idx_to_inventor = {i: name for i, name in enumerate(all_inventors)}
idx_to_topic = {i + num_inventors: tid for i, tid in enumerate(all_topics)}

In [28]:
# --- 4. 予測スコアの計算とデータフレーム化 ---

inventor_indices = torch.arange(num_inventors, device=device)
topic_indices = torch.arange(num_inventors, total_nodes, device=device)

predicted_links = []

# 発明者-トピックの総当たり戦
for inv_idx in inventor_indices:
    
    z_c = z_pred[inv_idx].unsqueeze(0).expand(num_topics, -1)
    z_p = z_pred[topic_indices]
    combined = torch.cat([z_c, z_p], dim=1)
    scores = model.link_predictor(combined).squeeze()
    
    probabilities = torch.sigmoid(scores).detach().cpu().numpy()
    
    inventor_name = idx_to_inventor[inv_idx.item()]
    
    for i, prob in enumerate(probabilities):
        topic_global_idx = topic_indices[i].item()
        topic_id = idx_to_topic[topic_global_idx]
        
        is_correct = (inv_idx.item(), topic_global_idx) in actual_links_set

        predicted_links.append({
            'inventor': inventor_name,
            'topic_id': topic_id,
            'predicted_score': prob,
            'is_actual_link_in_t+1': is_correct # 正解フラグ
        })

In [179]:
# --- 5. データフレーム化と表示 ---

prediction_df = pd.DataFrame(predicted_links)
print("\n--- 予測結果のデータフレーム（上位10件） ---")

# スコアの高い順にソートし、正解フラグを確認
top_predictions = prediction_df.sort_values(by='predicted_score', ascending=False)
print(top_predictions)

--- 予測結果のデータフレーム（上位10件） ---
       inventor  topic_id  predicted_score  is_actual_link_in_t+1
93780     塚田  乙         0         0.999909                  False
144530    山口　健一         0         0.999907                  False
174250   平山  哲也         0         0.999904                  False
278180    生野　雅昭         0         0.999902                  False
19250     中村　喜和         0         0.999901                  False
...         ...       ...              ...                    ...
116209     安藤　亙         9         0.697698                  False
281906    田中　誠司         6         0.697171                  False
172706     布川　修         6         0.687947                  False
172709     布川　修         9         0.687079                  False
304786     福田　航         6         0.684780                  False

[396270 rows x 4 columns]

In [180]:
# 文字列 'True' ではなく、ブール値の True を使用します
correct_predictions = prediction_df[prediction_df['is_actual_link_in_t+1'] == True]

print("--- 実際に t+1 期間でリンクが形成された（正解）データ ---")

# スコアの高い順にソートして表示
# 正解データの中でも、モデルが高いスコアを出したものを確認すると、モデルの学習状況がわかります。
print(correct_predictions.sort_values(by='predicted_score', ascending=False).head(10))

# 正解データの総数
print(f"\n抽出された正解リンクの総数: {len(correct_predictions)}")

--- 実際に t+1 期間でリンクが形成された（正解）データ ---
       inventor  topic_id  predicted_score  is_actual_link_in_t+1
53150     児玉　廣之         0         0.999889                   True
192020    星野　勇門         0         0.999885                   True
199410    末吉　祥平         0         0.999883                   True
480     ▲柳▼下　太志         0         0.999882                   True
153230    山田　真也         0         0.999881                   True
90690     堀　佐和子         0         0.999880                   True
304940    福田　雄介         0         0.999879                   True
161570    岩村　文敬         0         0.999878                   True
229120     森　正志         0         0.999877                   True
50070     佐藤　高央         0         0.999876                   True

抽出された正解リンクの総数: 69991

In [181]:
import pandas as pd
from sklearn.metrics import roc_auc_score, average_precision_score

y_true = prediction_df['is_actual_link_in_t+1'].values
y_scores = prediction_df['predicted_score'].values

# 1. AUC Score (全体でのランキングの総合性能)
# 1.0に近いほど良い。これが「全体での正解率」の最も適切な指標です。
auc_score = roc_auc_score(y_true, y_scores)
print(f"1. AUC Score (全体でのランキング性能): {auc_score:.4f}")

# 2. Average Precision (AP)
# 正例の少ないデータセットでの実用的な予測性能。1.0に近いほど良い。
ap_score = average_precision_score(y_true, y_scores)
print(f"2. Average Precision (AP): {ap_score:.4f}")

1. AUC Score (全体でのランキング性能): 0.5597
2. Average Precision (AP): 0.1878

### 補足: Falseなのにスコアが高い？？

In [1]:
# 最小値、平均値、中央値を確認
print(prediction_df['predicted_score'].describe())

# ヒストグラムで分布を可視化（すべてが1.0付近に張り付いているか確認）
import matplotlib.pyplot as plt
prediction_df['predicted_score'].hist(bins=50)
plt.show()

NameError: name 'prediction_df' is not defined

In [171]:
# 2つの異なる年のグラフデータで、ノード数が違う、あるいは同じIDが指す人物が違う可能性を疑う
keys = sorted(graph_dict.keys())
print(f"Year {keys[0]} nodes: {graph_dict[keys[0]].num_nodes}")
print(f"Year {keys[1]} nodes: {graph_dict[keys[1]].num_nodes}")

Year 2000 nodes: 39637
Year 2001 nodes: 39637

In [133]:
# 学習後のモデルで確認
model.eval()
with torch.no_grad():
    # 最新の年などのデータを使う
    last_year = years[-1]
    data = graph_dict[last_year].to(device)
    
    # エンコードして z を取得
    z, _, _ = model.encode(data.edge_index, data.edge_weight)
    
    # ノルム（ベクトルの長さ）の平均を表示
    print(f"Average Vector Norm: {z.norm(dim=1).mean().item():.4f}")
    print(f"Max Vector Value: {z.max().item():.4f}")

Average Vector Norm: 0.2619
Max Vector Value: 10.4970

### データが悪いのかモデルが悪いのか？

In [173]:
from sklearn.metrics import roc_auc_score
import torch.nn.functional as F

model.eval()
with torch.no_grad():
    # 最新の学習データ（例: 最後の年）
    year = years[-1]
    data = graph_dict[year].to(device)
    
    # 1. エンコード
    z, _, _ = model.encode(data.edge_index, data.edge_weight)
    
    # 2. 「現在の」リンクを正しくスコアリングできるかチェック
    # 正例スコア
    pos_score = model.decode(z, data.edge_index).cpu().numpy()
    
    # 負例スコア（正例と同じ数だけランダム生成）
    neg_edge_index = negative_sampling(data.edge_index, num_nodes=data.num_nodes, num_neg_samples=len(pos_score))
    neg_score = model.decode(z, neg_edge_index).cpu().numpy()
    
    # AUC計算
    y_true = [1] * len(pos_score) + [0] * len(neg_score)
    y_scores = np.concatenate([pos_score, neg_score])
    
    recon_auc = roc_auc_score(y_true, y_scores)

    if recon_auc >= 0.8:
        print(f"Reconstruction AUC (現状復元能力): {recon_auc:.4f} GCN（エンコーダ）は正常。悪いのは「未来予測（predict_future）」の部分")
    elif recon_auc < 0.6 and recon_auc >= 0.4:
        print(f"Reconstruction AUC (現状復元能力): {recon_auc:.4f} データセットの作り方（IDズレなど）か、GCNの構造自体に問題あり。")

Reconstruction AUC (現状復元能力): 0.8997 GCN（エンコーダ）は正常。悪いのは「未来予測（predict_future）」の部分

Year 2000 nodes: 39637
Year 2001 nodes: 39637

### Precisionが低いので， トピックの数(topic数=8)を減らして実験 (topic_info3.csvを使用)

In [ ]:
y_true

### 熊谷組の発明者を特定して，年次の動きを見てみよう

In [183]:
df

,patent_number,patent_name,date,corporation,ipc,lead_ipc,fi,fterm,keyword,description,year,month,description_embedding,metadata_embedding,lead_inventor,inventors,year_month,topic_id,sim_score
0,特開2001-209692,施設管理システム,200001,['清水建設株式会社'],"['G06F 17/30 (2006.01)', 'G06Q 50/00 (...",G06F 17/30 (2006.01),"['G06F 17/30 170C', 'G06F 17/60 122C', 'G0...","['5B049BB05', '5B049CC02', '5B049CC45', '5B049...","['情報', 'すべて', '有効']",施設施工者が施設管理の情報をすべてにわたりデジタル情報化し、施設所有者に有効な施設管理情報を...,2000,1,"[0.03135940060019493, -0.0030927385669201612, ...",[ 0.2919243 -0.18772289 0.21053162 0.224033...,中島 亨,"中島 亨,竹島育朗",2000-01-01,14,0.904562
1,特開2001-205110,ドラフトチャンバ,200001,['大成建設株式会社'],[],B01L 1/00 (2006.01),[],[],"['化学物質', '作業室', '空調機', '清浄', '作業環境', '実験']",化学物質を取り扱うためのフードを備えたドラフトチャンバにおいて、作業室に空調設備を設けなくて...,2000,1,"[0.013121270574629307, -0.02321396768093109, -...",[ 0.27802473 -0.2309001 0.12717132 0.175692...,森内 裕之,森内 裕之,2000-01-01,29,0.910601
2,特開2001-206757,コンクリート組成物及びトンネル覆工工法,200001,['西松建設株式会社'],"['E21D 11/10 (2006.01)', 'C04B 28/02 (...",E21D 11/10 (2006.01),"['E21D 11/10 D', 'E21D 11/10 Z', 'C0...","['2D055DB00', '2D055KA00', '4G012PA27', '4G012...","['吹付けコンクリート', '品質', 'コストダウン', '作業環境', 'コンクリート組...",吹付けコンクリートの品質、施工性を向上させると共に、コストダウンを達成し、さらには口内粉塵の...,2000,1,"[0.0016511422581970692, 0.016119062900543213, ...",[ 0.30306432 -0.20834202 0.12808324 0.177891...,田浦 一英,"田浦 一英,山本 康博,藤川 可",2000-01-01,27,0.941194
3,特開2001-207423,後退パラペット型堤体の衝撃波力低減工法,200001,"['五洋建設株式会社', '中国電力株式会社']",['E02B 3/06 (2006.01)'],E02B 3/06 (2006.01),['E02B 3/06 301'],"['2D018BA11', '2D118AA11', '2D118DA01', '2D118...","['従来', '作用']",従来の後退パラペット型堤体においては、後退パラペットに作用する波力および転倒モーメントが大き...,2000,1,"[0.03772636130452156, 0.0183484498411417, -0.0...",[ 0.23017973 -0.32329643 0.08356746 0.327914...,関本 恒浩,"関本 恒浩,森屋 陽一,佐貫 宏,川俣 奨,泉 雄士,金田 時義,藤原 茂範,平岡 順...",2000-01-01,12,0.888276
4,特開2001-208409,空調用の流路切換装置及びそれを備えた空調機,200001,"['株式会社日建設計', '新晃工業株式会社']",['F24F 13/02 (2006.01)'],F24F 13/02 (2006.01),['F24F 13/02 D'],"['3L080AA02', '3L080AA04']","['空調システム', '流路']",空調システムに使用される流路の切換装置を簡略化する,2000,1,"[0.009848109446465969, 0.027212440967559814, -...",[ 0.25761563 -0.20579714 0.19196749 0.156607...,橋本 直樹,"橋本 直樹,稲川 健",2000-01-01,29,0.918571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42784,特開2021-101101,水路堆積物除去装置及び水路堆積物除去方法,202104,['東洋建設株式会社'],"['E02B 5/00 (2006.01)', 'B08B 1/04 (...",E03F 9/00 (2006.01),"['E02B 5/00 Z', 'B08B 1/04', 'E02B 15/0...",['2D025AA00'],"['駆動力', '堆積物', '掘削', '除去']",大きな駆動力を要することなく、堆積物を効率的に掘削して除去する,2021,4,"[0.04034804180264473, 0.017458472400903702, -0...",[ 0.34501505 -0.28883272 0.16848534 0.178671...,田中 啓之,"田中 啓之,宮原 和仁,森田 研志",2021-04-01,8,0.942012
42785,特開2021-119296,プレキャスト構造部材と経時硬化材の連結構造の構築方法,202105,"['オリエンタル白石株式会社', '株式会社ガイアート', '株式会社熊谷組', 'ジオスタ...",['E01D 19/12 (2006.01)'],E01D 19/12 (2006.01),['E01D 19/12'],"['2D059AA14', '2D059GG55']","['簡単', '作業手順', '養生期間', '施工期間', '連結構造', '構築方法']",簡単な方法により作業手順や養生期間を削減して施工期間を短縮するとともに、凹部のひび割れ耐力を...,2021,5,"[0.007959448732435703, 0.004999454133212566, -...",[ 0.24111861 -0.24822187 0.23449725 0.169212...,正司 明夫,"正司 明夫,大谷 悟司,櫻井 正之,渡邊 輝康,下中村 圭太,高松 芳徳",2021-05-01,2,0.936310
42786,特開2021-121724,構造物補強用部材及び継手構造,202105,"['東日本旅客鉄道株式会社', '清水建設株式会社']","['E04G 23/02 (2006.01)', 'E01D 22/00 (...",E04G 23/02 (2006.01),"['E04G 23/02 F', 'E01D 22/00 B', 'E0...","['2D059AA03', '2D059GG40', '2D059GG55', '2E176...","['継手部材', '加工手間', '施工手間', '大幅']",継手部材の加工手間と施工手間を大幅に軽減することを可能にする構造物補強用部材を提供する,2021,5,"[0.007658788003027439, 0.004220247268676758, -...",[ 0.26992404 -0.19907099 0.14545646 0.176773...,大郷 貴之,"大郷 貴之,伊東 典紀,久保 昌史,名倉 健二,杉橋 直行,前田 敏也,山下 裕司",2021-05-01,25,0.949135
42787,特開2021-121725,拡底部を備えた地下壁杭構造,202105,['大成建設株式会社'],"['E02D 5/30 (2006.01)', 'E02D 5/48 (...",E02D 5/30 (2006.01),"['E02D 5/30 Z', 'E02D 5/48', 'E02D 5/2...","['2D041AA01', '2D041BA22', '2D041CB03', '2D041...","['拡底部', '壁杭', '拡底部', '耐力', '支持力']",拡底部を備えた壁杭の拡底部の耐力が低下することを解消し、高支持力の地下壁杭を形成すること,2021,5,"[-0.0023702960461378098, 0.015371913090348244,...",[ 0.2966622 -0.19690101 0.11967281 0.165533...,平山 哲也,"平山 哲也,岩田 曉洋,渡邉 祐一,渡邊 徹",2021-05-01,19,0.944283
42788,登実第3233709号,平パレット及び平パレットの免振構造,202106,['大成建設株式会社'],[],B65D 19/38 (2006.01),[],[],"['地震力', '作用', '安価', 'パレット', 'パレット']",強い地震力が作用した場合に減振効果が高く、簡易な構造かつ安価な平パレット及び平パレットの免振...,2021,6,"[0.034338876605033875, 0.005877140909433365, -...",[ 0.23753199 -0.18755217 0.08742531 0.204571...,高木 政美,"高木 政美,塚田 乙",2021-06-01,23,0.942340

In [80]:
TARGET_CORP = '株式会社熊谷組'

kumagai_df = df[df['corporation'].astype(str).str.contains(TARGET_CORP)].copy()
kumagai_df.head()

,patent_number,patent_name,date,corporation,ipc,lead_ipc,fi,fterm,keyword,description,year,month,description_embedding,metadata_embedding,lead_inventor,inventors,year_month,topic_id,sim_score
35,特開2001-200508,ラーメン橋の免震構造,200001,['株式会社熊谷組'],"['E01D 19/02 (2006.01)', 'E01D 101/00 (...",E01D 19/02 (2006.01),"['E01D 19/02', 'E01D101:00']","['2D059AA03', '2D059GG01', '2D059GG13', '2D059...","['高さ寸法', '橋脚', '免震効果', '免震構造']",高さ寸法の大きい橋脚を有するラーメン橋梁についても、十分な免震効果を発揮する免震構造を提供すること,2000,1,"[0.01587533950805664, 0.0007495990139432251, -...",[ 2.05702335e-01 -3.38475287e-01 8.04397315e-...,鈴木 猛康,"鈴木 猛康,金子 誉,勝川 藤太",2000-01-01,19,0.923898
60,特開2001-207530,建築物,200001,['株式会社熊谷組'],"['E02D 27/34 (2006.01)', 'E04B 1/18 (...",E02D 27/34 (2006.01),"['E02D 27/34 B', 'E04B 1/18 A', 'E0...","['2D046DA11', '2E139AA01', '2E139AB01', '2E139...","['設計', '応力状態', '地下階', '建築物']",設計時の構造解析で応力状態を容易に把握することができる、地下階を有する建築物を提供すること,2000,1,"[0.010046501643955708, 0.0026959727983921766, ...",[ 0.22702494 -0.22875622 0.14302126 0.219681...,前川 利雄,"前川 利雄,岡野 創,福島 寛二",2000-01-01,19,0.924737
110,特開2001-193192,壁用プレキャストコンクリート板および壁ならびにその構築方法,200001,"['株式会社熊谷組', '日本カイザー株式会社']","['E04B 2/56 (2006.01)', 'E04C 2/30 (...",E04B 2/56 (2006.01),['E04B 2/56 633A'],"['2E002FB03', '2E002GA01', '2E002KA01', '2E002...","['見栄え', '簡単', 'プレキャストコンクリート板', '構築方法']",見栄えが良く、かつ簡単に構築できる壁用プレキャストコンクリート板および壁ならびにその構築方法...,2000,1,"[0.023176118731498718, 0.015833532437682152, -...",[ 0.26981902 -0.24196342 0.23455536 0.156270...,佐藤 玲圭,"佐藤 玲圭,長原 彰彦",2000-01-01,1,0.935542
131,特開2001-191321,スラリーの製造方法および製造装置,200001,['株式会社熊谷組'],[],B28C 5/06 (2006.01),[],"['4G056AA07', '4G056CC01']","['大量', 'スラリー', '製造', '装置']",一時に大量のスラリーを製造するための方法および装置を提供すること,2000,1,"[-0.0012541625183075666, 0.001501165796071291,...",[ 0.38522303 -0.34202522 0.2406198 0.308403...,濱田 尚人,"濱田 尚人,波多江 勝,西山 勝栄,吉村 丈晴",2000-01-01,0,0.911349
136,特開2001-193381,プラズマ破壊装置およびこれを用いた破壊方法,200001,"['住友電気工業株式会社', '株式会社熊谷組', '奥村組土木興業株式会社']","['E21C 37/18 (2006.01)', 'B02C 19/00 (...",E21C 37/18 (2006.01),"['E21C 37/18', 'B02C 19/00 Z']","['2D065EA26', '4D067CG01', '4D067GA02']","['パルス', '反射', 'エネルギー', 'ロス']",衝撃波の反射などによるエネルギーのロスや破壊電極の破損などを低減できるプラズマ破壊方法および...,2000,1,"[0.037919171154499054, 0.013051414862275124, -...",[ 0.29223874 -0.2270223 0.0989247 0.174623...,桑原 雅裕,"桑原 雅裕,岡崎 徹",2000-01-01,9,0.921080

In [81]:
# 筆頭発明者（lead_inventor）の一覧を取得
inventors_list = kumagai_df['lead_inventor'].unique()
inventors_list

array(['鈴木\u3000猛康', '前川\u3000利雄', '佐藤\u3000玲圭', '濱田\u3000尚人',
       '桑原\u3000雅裕', '渡邉\u3000弘行', '北山\u3000裕康', '加藤\u3000武彦',
       '遠藤\u3000哲夫', '大見\u3000忠弘', '富永\u3000克己', '手島\u3000久雄',
       '大堀\u3000卓', '山口\u3000高弘', '阿部\u3000茂木', '横塚\u3000享', '築\u3000龍彦',
       '岡田\u3000喬', '新井\u3000勘', '反後\u3000堯雄', '塩屋\u3000儀徳', '内藤\u3000充洋',
       '吉松\u3000賢二', '神山\u3000英雄', '益田\u3000光雄', '伊藤\u3000洋',
       '波多江\u3000勝', '田中\u3000浩和', '高田\u3000秀行', '時岡\u3000誠剛',
       '鵜飼\u3000達郎', '高見沢\u3000滋', '大脇\u3000雅直', '遠嶽\u3000信幸',
       '岡崎\u3000徹', '宇野\u3000定雄', '片岡\u3000秀樹', '石田\u3000和夫',
       '松本\u3000嘉司', '中野\u3000薫', '西山\u3000勝栄', '村西\u3000正紀',
       '高橋\u3000良文', '上村\u3000正己', '柴田\u3000浩彦', '川原\u3000一則',
       '達\u3000弘文', '松村\u3000修治', '岡野\u3000創', '木村\u3000裕喜', '大川\u3000慶直',
       '渡部\u3000武彦', '柳澤\u3000忠智', '高橋\u3000信行', '前村\u3000辰二',
       '山下\u3000恭弘', '傳\u3000慶一', '川嶋\u3000潤二', '杉山\u3000雅彦',
       '渡辺\u3000英彦', '羽野\u3000弘規', '安川\u3000良博', '盛岡\u3000実',
       '川上\u3000廣美', '川口\u3000謙治', '森田\u3000知志', '増子\u3000寛',
       '三木\u3000博史', '上間\u3000紀幸', '河村\u3000彰男', '大川\u3000出',
       '田辺\u3000忠顯', '三浦\u3000政美', '緑川\u3000光正', '名波\u3000義昭',
       '渡辺\u3000則雄', '高山\u3000利彦', '三浦\u3000悟', '垣内\u3000幸雄',
       '御手洗\u3000良夫', '石口\u3000真実', '大門\u3000信之', '原岡\u3000充',
       '小松原\u3000修義', '濱田\u3000真', '木戸\u3000義和', '酒井\u3000章', '霜鳥\u3000明',
       '川越\u3000健', '阿部\u3000健一', '細田\u3000一樹', '藤木\u3000広一',
       '飯利\u3000昌人', '大坪\u3000紀之', '光石\u3000一成', '庄田\u3000政弘',
       '大谷\u3000多香', '岡村\u3000廣作', '重松\u3000篤', '門倉\u3000伸行',
       '佐藤\u3000英明', '長谷川\u3000清光', '渡邉\u3000公浩', '渡邊\u3000二夫',
       '土肥\u3000輝明', '福島\u3000康典', '杉山\u3000武', '関谷\u3000重樹',
       '山本\u3000清和', '森\u3000利弘', '滝沢\u3000賢一', '坂本\u3000敏彦',
       '徳岡\u3000康夫', '神田\u3000亮', '澤邊\u3000繁克', '麻生\u3000康弘',
       '高木\u3000秀和', '河内\u3000卓也', '執行\u3000信', '真下\u3000英人',
       '伊藤\u3000隆一', '萩原\u3000幸男', '石橋\u3000久義', '松田\u3000和美',
       '岩永\u3000茂治', '森\u3000雅孝', '岩井\u3000孝幸', '中澤\u3000言一',
       '沢田\u3000研自', '中川\u3000正俊', '小合\u3000英男', '小野塚\u3000仁',
       '岩村\u3000栄世', '小泉\u3000淳', '田辺\u3000大次郎', '菅\u3000一雅',
       '横山\u3000義憲', '有岡\u3000正樹', '杉本\u3000旭', '服部\u3000誠', '本多\u3000文夫',
       '西村\u3000清亮', '河越\u3000勝', '満井\u3000淳一', '安部\u3000良夫', '滑\u3000秀紀',
       '古川\u3000敦', '村岡\u3000憲司', '荒木\u3000智勇', '大越\u3000靖広',
       '村山\u3000健冶', '松村\u3000高宏', '山内\u3000一生', '平生\u3000進一',
       '日高\u3000徳弘', '森\u3000康雄', '北嶋\u3000圭二', '小林\u3000茂樹',
       '大谷\u3000誠一', '亀井\u3000隆仁', '丸居\u3000良吉', '上井\u3000隆',
       '浅松\u3000裕吾', '▲丈▼達\u3000俊夫', '江藤\u3000俊文', '山森\u3000規安',
       '上杉\u3000英樹', '青野\u3000孝行', '繁\u3000修二', '篠原\u3000巌', '森\u3000不可止',
       '松田\u3000敏', '伊藤\u3000彰彦', '伊藤\u3000隆', '井上\u3000年史', '武田\u3000邦夫',
       '佐藤\u3000孝一', '爲沢\u3000長雄', '鈴木\u3000宏和', '西村\u3000洋一',
       '加藤\u3000英康', '仲宗根\u3000淳', '岡市\u3000光司', '冨金原\u3000正裕',
       '西村\u3000秀和', '飯田\u3000廣臣', '大川\u3000将玄', '北原\u3000成郎',
       '伊東\u3000繁', '近藤\u3000誠一', '山田\u3000浩史', '太刀川\u3000丈爾',
       '中島\u3000潤二', '小島\u3000時和', '若山\u3000裕泰', '冨田\u3000憲治',
       '佐藤\u3000聡', '清水\u3000利郎', '溝手\u3000一憲', '田中\u3000繁', '羽迫\u3000英男',
       '小林\u3000宏光', '焼田\u3000真司', '芦沢\u3000健', '大脇雅直', '石川\u3000義治',
       '佐々木\u3000静郎', '村上\u3000順也', '増澤\u3000伸司', '町田\u3000憲泰',
       '高木\u3000仁之', '柳澤\u3000和典', '橋本\u3000修', '安藤\u3000康彦', '青野\u3000隆',
       '小川\u3000敦', '村松\u3000繁', '斎藤\u3000章司', '今泉\u3000治郎', '千代\u3000啓三',
       '木村\u3000晃', '今田\u3000徹', '金森\u3000誠治', '永島\u3000仁', '嶋田\u3000浩一',
       '堀川\u3000朗彦', '新屋敷\u3000隆', '広瀬\u3000俊文', '山下\u3000文章',
       '祖父江\u3000猛', '岩佐\u3000幹生', '杉本\u3000靖夫', '伏屋\u3000貴文',
       '和田\u3000章', '久保田\u3000謙三', '大学\u3000淳', '原\u3000守哉',
       '藤▲崎▼\u3000裕三', '内藤\u3000敏', '田中\u3000淳一', '西垣\u3000和弘',
       '渡邉\u3000則雄', '堀田\u3000謙一', '上木\u3000弘毅', '西村\u3000昭彦',
       '大本\u3000晋士郎', '牛腸\u3000明', '渡邊\u3000則雄', '小野\u3000博康',
       '西内\u3000美宣', '岡▲崎▼\u3000英樹', '蔵増\u3000明生', '反田\u3000佳希',
       '清宮\u3000理', '田中\u3000一', '山中\u3000弘', '町屋\u3000孝浩', '西\u3000治郎',
       '亀若\u3000三起', '三上\u3000誠', '野中\u3000英', '井口\u3000学', '小椋\u3000明仁',
       '海老沢\u3000勇', '片山\u3000政弘', '斉藤\u3000大樹', '鴇田\u3000隆', '上東\u3000泰',
       '坂西\u3000孝仁', '高久\u3000節夫', '伊藤\u3000省二', '芳賀\u3000宏',
       '阿部\u3000高広', '田中\u3000清隆', '鰐渕\u3000憲昭', '▲辻▼\u3000賢之',
       '小山\u3000幸則', '山下\u3000浩', '大平\u3000茂', '谷村\u3000幸裕', '吉敷\u3000祥一',
       '▲高▼木\u3000淳次', '龍岡\u3000文夫', '波田\u3000雅也', '金田\u3000則夫',
       '近藤\u3000祐輔', '佐野\u3000大作', '金子\u3000治', '森田\u3000栄治',
       '岡崎\u3000紀明', '鈴木\u3000雄吾', '正司\u3000明夫', '大野\u3000雅紀',
       '佐藤\u3000永', '平井\u3000禎二', '土路生\u3000修三', '西村\u3000和夫',
       '遠藤\u3000正美', '諏訪\u3000和徳', '細川\u3000清', '小林\u3000敬', '舘石\u3000和雄',
       '久保\u3000隆司', '増\u3000澤\u3000伸\u3000司', '丸山\u3000敏彦', '松岡\u3000直人',
       '田邉\u3000大次郎', '池亀\u3000恵美子', '吉田\u3000健治', '熊沢\u3000紀之',
       '樋口\u3000優香', '中山\u3000猛', '丹羽\u3000智久', '加藤\u3000優輝',
       '本田\u3000和久', '榊原\u3000健人', '石岡\u3000拓', '新井\u3000寿昭',
       '郡司\u3000康浩', '蒋\u3000宇静', '宮島\u3000英樹', '中原\u3000学', '渡邊\u3000輝康',
       '佐藤\u3000英規', '吉澤\u3000尚志', '山本\u3000勝', '久保\u3000幹', '臼井\u3000宏和',
       '田中  輝雄', '工藤\u3000守', '阿部  高広', '森下\u3000功', '浅田\u3000章一',
       '冨樫\u3000淳輝', '小笠原\u3000勝', '黒木\u3000拓', '渡辺  英彦', '梅村\u3000勝',
       '森本\u3000明寛', '日暮\u3000徹', '酒井\u3000祐介', '富田\u3000努', '張\u3000海華',
       '中村\u3000孝道', '前田\u3000匡樹', '谷口\u3000惠梨', '露木\u3000保男',
       '宮本\u3000圭一', '石濱\u3000茂崇', '野田\u3000憲太郎', '下川\u3000智男',
       '清野\u3000和徳', '大和矢\u3000麻起', '西宮\u3000幸洋', '後藤\u3000治彦',
       '児玉\u3000耕太', '小野\u3000哲男', '植田\u3000芳昭', '白水\u3000晃生',
       '都祭\u3000弘幸', '西窪\u3000久弥', '尾崎\u3000健一郎', '鈴木\u3000健',
       '三宅\u3000朗彦', '村上  順也', '川崎\u3000了', '青木  浩幸', '坂西  孝仁'],
      dtype=object)

In [82]:
# 発明者一覧をデータフレームで表示
df_inventors = pd.DataFrame(inventors_list, columns=['筆頭発明者'])
df_inventors

      筆頭発明者
0     鈴木　猛康
1     前川　利雄
2     佐藤　玲圭
3     濱田　尚人
4     桑原　雅裕
..      ...
363   三宅　朗彦
364  村上  順也
365    川崎　了
366  青木  浩幸
367  坂西  孝仁

[368 rows x 1 columns]

In [83]:
# 以下の変数を次のセルで使用します
inventors_to_track = kumagai_df['lead_inventor'].unique()
patent_data_to_analyze = kumagai_df.copy()

In [84]:
# =========================================================================
# 発明者ごとのトピック履歴確認
# =========================================================================

# 確認したい発明者の名前を指定してください (例: '熊谷　太郎' or '田中　花子')
TARGET_INVENTOR = '濱田　尚人' 

if 'patent_data_to_analyze' in globals():
    inventor_history = patent_data_to_analyze[
        patent_data_to_analyze['lead_inventor'] == TARGET_INVENTOR
    ].copy()

    if inventor_history.empty:
        print(f"発明者 '{TARGET_INVENTOR}' の筆頭特許は見つかりませんでした。")
    else:
        # 必要な列を抽出して表示
        display_cols = [
            'year_month', 
            'patent_name', 
            'topic_id', 
            'sim_score',
            'description', 
            'corporation'
        ]

        history_df = inventor_history[[
            'year_month', 
            'patent_name', 
            'topic_id',
            'sim_score',
            'description'
        ]].sort_values(by='year_month')
        
        print(f"### 発明者: {TARGET_INVENTOR} のトピック活動履歴 ###")
        print(history_df)
        
        # どのトピックに最も関与しているか
        top_topics = history_df['topic_id'].value_counts()
        print("\n--- 関与トピックの件数ランキング ---")
        print(top_topics)

else:
    print("データフレーム `patent_data_to_analyze` が前のセルで準備されていません。")

### 発明者: 濱田　尚人 のトピック活動履歴 ###
       year_month         patent_name  topic_id  sim_score  \
131    2000-01-01    スラリーの製造方法および製造装置         0   0.911349
353    2000-02-01               ロータリ弁        18   0.922263
619    2000-03-01        地盤の改良方法および装置         0   0.938987
623    2000-03-01         骨材等を用いた置換工法         7   0.917666
42047  2019-11-01  微細藻類培養池及び微細藻類の培養方法        13   0.937114

                                             description
131                     一時に大量のスラリーを製造するための方法および装置を提供すること
353    流動抵抗または流動エネルギ損失のより小さいロータリ弁、特に前記地盤改良装置の中空体に供給され...
619                        より良好な地盤改良を行うための方法および装置を提供すること
623            骨材とスラリを用いた埋め戻し工法でのスラリの充填性及び骨材間の噛合せとを向上させる
42047  簡単な構成で水流を効率的に攪拌し、培養池の底面に沈殿堆積する微細藻類の量を低減することのでき...

--- 関与トピックの件数ランキング ---
topic_id
0     2
18    1
7     1
13    1
Name: count, dtype: int64